name: Create Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.x'
    - uses: actions/checkout@v1
    - name: Get dependencies
      run: go mod download
    - name: Run tests
      run: go test
    - name: Build and archive
      run: |
        GOOS=linux go build -ldflags='-s -w' -trimpath -o hello
        GZIP=-9 tar czvf hello.tar.gz hello
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Upload artifact
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to
        # get its outputs object, which include a `upload_url`. See this blog
        # post for more info:
        # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hello.tar.gz
        asset_name: hello.tar.gz
        asset_content_type: application/gzip
