name: Test suite
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.5'
    - uses: actions/checkout@v1
    - name: Get dependencies
      run: go mod download
    - name: Run tests
      run: go test